version: "3.9"
services:
  n3tk-auth:
    container_name: n3tk-auth
    image: quay.io/keycloak/keycloak:24.0.2
    command: ["start-dev", "--http-port", "8180"]
    environment:
      TZ: Asia/Ho_Chi_Minh
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8180"
  n3tk-db:
    container_name: n3tk-db
    image: mysql:8.0
    environment:
      TZ: Asia/Ho_Chi_Minh
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3306:3306"
  n3tk-product:
    container_name: n3tk-product
    build: n3tk-product
    environment:
      TZ: Asia/Ho_Chi_Minh
      PORT: 8081
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/n3tk/core/products/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - n3tk-db