version: "3.9"
services:
  # mysql database
  mysql-db:
    container_name: n3tk-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart
    ports:
      - "3306:3306"
  # spring boot app
  spring-boot-app:
    container_name: n3tk-app
    build: resource-server
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MAILGUN_DOMAIN_NAME: ${MAILGUN_DOMAIN_NAME}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_SERVICE_SID: ${TWILIO_SERVICE_SID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db