version: "3.9"
services:
  # mysql database
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart
    ports:
      - "3300:3306"
  # spring boot app
  spring-boot-app:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - mysql-db